spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-calm-field-alxy4hro-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_f9H8grFMUhJW}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

# JWT
jwt.secret=${JWT_SECRET:QXNzZXRUcmFjazIwMjRTdXBlclNlY3JldEtleUZvckpXVFNpZ25pbmchTXVzdEJlMzJDaGFycw==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

